# Generated by Django 5.0.2 on 2025-05-03 13:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], max_length=2)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.PositiveIntegerField()),
                ('annual_average', models.FloatField()),
                ('appreciation', models.CharField(max_length=50)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.student')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('is_group', models.BooleanField(default=False)),
                ('parent_ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='belletin.ue')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('mc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.student')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.ue')),
            ],
            options={
                'unique_together': {('student', 'ue')},
            },
        ),
    ]
