# Generated by Django 5.0.2 on 2025-05-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0003_course_gradecomponent_grademodificationlog_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.DateField(),
        ),
    ]
