# Generated by Django 5.0.2 on 2025-05-03 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0004_alter_academicyear_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('date_scheduled', models.DateTimeField()),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée')], default='PENDING', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.academicyear')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.promotion')),
            ],
            options={
                'unique_together': {('promotion', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_president', models.BooleanField(default=False)),
                ('departments', models.ManyToManyField(related_name='jury_members', to='belletin.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(default=0)),
                ('credits_obtained', models.PositiveIntegerField(default=0)),
                ('auto_decision', models.CharField(choices=[('ADMITTED', 'Admis'), ('REMEDIAL', 'Rattrapage'), ('FAILED', 'Ajourné')], max_length=20)),
                ('final_decision', models.CharField(blank=True, choices=[('ADMITTED', 'Admis'), ('REMEDIAL', 'Rattrapage'), ('FAILED', 'Ajourné')], max_length=20, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.deliberation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.student')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('deliberation', 'student')},
            },
        ),
        migrations.CreateModel(
            name='DeliberationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_decision', models.CharField(choices=[('ADMITTED', 'Admis'), ('REMEDIAL', 'Rattrapage'), ('FAILED', 'Ajourné')], max_length=20)),
                ('new_decision', models.CharField(choices=[('ADMITTED', 'Admis'), ('REMEDIAL', 'Rattrapage'), ('FAILED', 'Ajourné')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.studentdeliberation')),
            ],
        ),
        migrations.CreateModel(
            name='DeliberationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.deliberation')),
                ('jury_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.jurymember')),
            ],
            options={
                'unique_together': {('deliberation', 'jury_member')},
            },
        ),
    ]
