# Generated by Django 5.0.2 on 2025-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0005_deliberation_jurymember_studentdeliberation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurymember',
            name='departments',
        ),
        migrations.AddField(
            model_name='jurymember',
            name='promotions',
            field=models.ManyToManyField(related_name='jury_members', to='belletin.promotion'),
        ),
    ]
