# Generated by Django 5.0.2 on 2025-05-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0006_remove_jurymember_departments_jurymember_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
