# Generated by Django 5.0.2 on 2025-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0007_deliberation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdeliberation',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
