# Generated by Django 5.0.2 on 2025-05-05 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0008_studentdeliberation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='moyenne',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='grade',
            name='resultat',
            field=models.CharField(default='NON VALIDÉ', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdeliberation',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True),
        ),
    ]
