# Generated by Django 5.0.2 on 2025-05-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belletin', '0009_grade_moyenne_grade_resultat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='belletin.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='belletin.academicyear'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('ADMITTED', 'Admis(e)'), ('REMEDIAL', 'Rattrapage'), ('FAILED', 'Ajourné(e)')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('credits_obtained', models.IntegerField(default=0)),
                ('average', models.FloatField(default=0)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belletin.academicyear')),
                ('from_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_histories', to='belletin.promotion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='belletin.student')),
                ('to_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_histories', to='belletin.promotion')),
            ],
        ),
    ]
